version: '2'

services:
  app:
    build: .
    command: npm run dev
    networks:
      - net
    depends_on:
      - mongodb
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/app
      - /home/app/node_modules

  mongodb:
    image: mongo:3.2.5
    ports:
      - "27017:27017"
    networks:
      - net

networks:
  net:
