version: '2'

services:
  app:
    build: .
    command: npm run dev
    depends_on:
      - mongodb
    ports:
      - "3003:3003"
    volumes:
      - .:/home/app
      - /home/app/node_modules

  mongodb:
    image: mongo:3.2.5
    ports:
      - "27017:27017"
