version: '2'

services:
  app:
    build: .
    networks:
      - net
    depends_on:
      - mongodb
    ports:
      - "${PORT}:${PORT}"

  mongodb:
    image: mongodb:3.2.5
    networks:
      - net

networks:
  net:
